# Generated by Django 4.0.3 on 2022-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='endTime',
            field=models.CharField(default='1647175751000', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='startTime',
            field=models.CharField(default='1647175751000', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='update_at',
            field=models.CharField(default='1647175751000', editable=False, max_length=20),
        ),
    ]
