# Generated by Django 4.0.3 on 2022-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interview_endtime_alter_interview_starttime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='duration',
        ),
        migrations.AlterField(
            model_name='interview',
            name='endTime',
            field=models.CharField(default='1647175927000', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='startTime',
            field=models.CharField(default='1647175927000', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='update_at',
            field=models.CharField(default='1647175927000', editable=False, max_length=20),
        ),
    ]
